# Generated by Django 4.0.6 on 2022-08-03 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_book_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Document',
        ),
    ]
