# Generated by Django 4.0.6 on 2022-08-03 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0005_book_delete_document'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Document',
        ),
    ]
