# Generated by Django 4.0.6 on 2022-08-03 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0007_remove_document_category_remove_document_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='email1',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='document',
            name='email2',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='document',
            name='email3',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='document',
            name='email4',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='document',
            name='email5',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
    ]
