# Generated by Django 4.0.6 on 2022-08-03 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0008_document_email1_document_email2_document_email3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='email1',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='document',
            name='email2',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='document',
            name='email3',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='document',
            name='email4',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='document',
            name='email5',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
